-- =============================================================================
-- 003_indexes.sql
-- Complete Index Documentation
-- =============================================================================
--
-- Every index defined in the codebase is documented here, organized by table.
--
-- Index sources:
--   - Column(..., index=True)        → SQLAlchemy auto-generated single-column indexes
--   - Column(..., unique=True)       → SQLAlchemy auto-generated unique indexes
--   - __table_args__ Index(...)      → Explicitly named composite/single indexes
--   - __table_args__ Index(unique=T) → Explicitly named unique indexes
--   - postgresql_using="gin"         → GIN index for full-text search
--
-- Naming conventions:
--   ix_<table>_<column>              → Auto-generated by SQLAlchemy
--   idx_<descriptive_name>           → Explicitly named in __table_args__
--
-- Source: backend/auth/auth_models.py (all commits up to HEAD)
-- =============================================================================


-- =============================================================================
-- TABLE: users
-- =============================================================================

-- Auto-generated single-column indexes (Column(..., index=True))
CREATE INDEX ix_users_email         ON users (email);          -- Also UNIQUE
CREATE INDEX ix_users_role          ON users (role);
CREATE INDEX ix_users_created_at    ON users (created_at);


-- =============================================================================
-- TABLE: query_logs
-- =============================================================================

-- Auto-generated single-column indexes (Column(..., index=True))
CREATE INDEX ix_query_logs_timestamp          ON query_logs (timestamp);
CREATE INDEX ix_query_logs_user_id            ON query_logs (user_id);
CREATE INDEX ix_query_logs_query_granularity  ON query_logs (query_granularity);
CREATE INDEX ix_query_logs_blocked            ON query_logs (blocked);
CREATE INDEX ix_query_logs_risk_level         ON query_logs (risk_level);

-- Composite indexes (__table_args__)
-- Added in Phase 1 (commit f6e0f09):
CREATE INDEX idx_query_logs_user_timestamp    ON query_logs (user_id, timestamp);
CREATE INDEX idx_query_logs_risk_blocked      ON query_logs (risk_level, blocked);

-- Added in Phase 3 (commit ffbccf5):
CREATE INDEX idx_query_logs_created           ON query_logs (timestamp);
CREATE INDEX idx_query_logs_user              ON query_logs (user_id);


-- =============================================================================
-- TABLE: conversations
-- Added in Phase 2 (commit 35ca000)
-- =============================================================================

-- Auto-generated single-column index
CREATE INDEX ix_conversations_user_id ON conversations (user_id);

-- Composite index (__table_args__)
-- Purpose: Fast sidebar query — fetch active convs for a user sorted by recency
CREATE INDEX idx_conversations_user_active_updated
    ON conversations (user_id, is_deleted, updated_at);


-- =============================================================================
-- TABLE: messages
-- Added in Phase 2 (commit 35ca000)
-- =============================================================================

-- Auto-generated single-column index
CREATE INDEX ix_messages_conversation_id ON messages (conversation_id);

-- Composite index (__table_args__)
-- Purpose: Ordered message retrieval for a conversation
CREATE INDEX idx_messages_conversation_created
    ON messages (conversation_id, created_at);


-- =============================================================================
-- TABLE: email_otps
-- Added in Phase 2 (commit 35ca000), indexes expanded in Phase 3
-- =============================================================================

-- Auto-generated single-column indexes
CREATE INDEX ix_email_otps_email      ON email_otps (email);
CREATE INDEX ix_email_otps_expires_at ON email_otps (expires_at);

-- Added in Phase 3 (commit ffbccf5):
CREATE INDEX ix_email_otps_created_at ON email_otps (created_at);

-- Composite indexes (__table_args__) — added in Phase 3 (commit ffbccf5)
CREATE INDEX idx_emailotp_email       ON email_otps (email);
CREATE INDEX idx_emailotp_created     ON email_otps (created_at);


-- =============================================================================
-- TABLE: rate_limit_counters
-- Added in Phase 3 (commit ffbccf5)
-- =============================================================================

-- Auto-generated single-column indexes
CREATE INDEX ix_rate_limit_counters_identifier   ON rate_limit_counters (identifier);
CREATE INDEX ix_rate_limit_counters_endpoint      ON rate_limit_counters (endpoint);
CREATE INDEX ix_rate_limit_counters_window_start  ON rate_limit_counters (window_start);

-- Composite indexes (__table_args__)
-- UNIQUE composite for UPSERT-based sliding window rate limiting
CREATE UNIQUE INDEX idx_rate_limiter_identifier_window
    ON rate_limit_counters (identifier, endpoint, window_start);
CREATE INDEX idx_rate_created ON rate_limit_counters (window_start);
CREATE INDEX idx_rate_ip      ON rate_limit_counters (identifier);


-- =============================================================================
-- TABLE: otp_request_limits
-- Added in Phase 3 (commit ffbccf5)
-- =============================================================================

-- Auto-generated single-column indexes
CREATE INDEX ix_otp_request_limits_email               ON otp_request_limits (email);
CREATE INDEX ix_otp_request_limits_ip_address           ON otp_request_limits (ip_address);
CREATE INDEX ix_otp_request_limits_request_timestamp    ON otp_request_limits (request_timestamp);

-- Composite indexes (__table_args__)
CREATE INDEX idx_otp_limit_email     ON otp_request_limits (email);
CREATE INDEX idx_otp_limit_ip        ON otp_request_limits (ip_address);
CREATE INDEX idx_otp_limit_timestamp ON otp_request_limits (request_timestamp);


-- =============================================================================
-- TABLE: system_metrics
-- Added in Phase 3 (commit ffbccf5)
-- =============================================================================

-- No additional indexes beyond the primary key.
-- metric_name is the primary key (VARCHAR).


-- =============================================================================
-- TABLE: documents
-- Added in Phase 4 (commit 4aa59b5)
-- =============================================================================

-- Auto-generated single-column index
CREATE INDEX ix_documents_source_file ON documents (source_file);  -- Also UNIQUE


-- =============================================================================
-- TABLE: chunks
-- Added in Phase 4 (commit 4aa59b5)
-- =============================================================================

-- Auto-generated single-column indexes
CREATE INDEX ix_chunks_doc_id       ON chunks (doc_id);
CREATE INDEX ix_chunks_page_number  ON chunks (page_number);

-- Composite/special indexes (__table_args__)
-- GIN index for PostgreSQL full-text search on TSVECTOR column
CREATE INDEX idx_chunks_tsv       ON chunks USING gin (tsv_content);
CREATE INDEX idx_chunks_doc_page  ON chunks (doc_id, page_number);


-- =============================================================================
-- TABLE: vector_maps
-- Added in Phase 4 (commit 4aa59b5)
-- =============================================================================

-- Auto-generated single-column index
CREATE INDEX ix_vector_maps_chunk_id ON vector_maps (chunk_id);  -- Also UNIQUE


-- =============================================================================
-- INDEX SUMMARY
-- =============================================================================
--
-- Explicitly defined indexes (via ORM code):              42
--   - Column(..., index=True)  single-column indexes:     24
--   - __table_args__ Index()   composite indexes:         14
--   - __table_args__ Index()   named single-column:        3
--   - UNIQUE composite index:                              1
--     (rate_limit_counters: identifier + endpoint + window_start)
--   - GIN index (full-text search):                        1
--     (chunks.tsv_content)
--
-- Implicit indexes (auto-created by PostgreSQL, NOT listed above):
--   - Primary key indexes:         10  (one per table)
--   - UNIQUE constraint indexes:    4  (users.email, query_logs.query_id,
--                                       documents.source_file, vector_maps.chunk_id)
--
-- Total indexes on a live PostgreSQL instance:  ~56
--   (42 explicit + ~14 implicit from PK/UNIQUE constraints)
--
-- Note: Some explicit indexes duplicate coverage with implicit UNIQUE
-- indexes (e.g., ix_users_email duplicates the index PostgreSQL auto-creates
-- for uq_users_email). This is consistent with the ORM model definitions.
-- =============================================================================

